development:
  adapter: postgresql
  encoding: unicode
  database: fantasy_dev
  pool: 5
  password:
  host: localhost
  port: 5432


test:
  adapter: postgresql
  encoding: unicode
  database: fantasy_test
  pool: 5
  password:
  host: localhost
  port: 5432